### ISSUE TITLE
License not included in install from PyPi

### ISSUE THREAD

**Issue by altendky** [hawkowl/incremental#26]
![image](https://cloud.githubusercontent.com/assets/543719/20351007/15528716-abdf-11e6-8d98-616ad36fc598.png)

I was going through the libraries I use to collect licenses since I distribute my application using `pyqtdeploy` on Windows and noticed that `incremental` did not seem to include it's own license when installed from PyPi.

**Comment by hawkowl** [comment]
None of the packages I know of include licenses in their installed copies, only the distributed artifacts (whl or .tar.gz), from a quick check of my site-packages. Not sure how I can do this in a standard way?
